dts: wb6: add gpio line names
wirenboard/linux pull request #114
Opened 2022-11-23 10:11 UTC by KraPete

2022-11-23 13:36 UTC, evgeny-boger requested changes
label абсолютно всегда должны совпадать с существующими на WB7, потому что они становятся частью неизменного api.

Как минимум W1 UP не совпал. Надо перепроверить все.

2022-11-23 13:43 UTC, KraPete commented
Я копировал из WB7. Если не было в WB7, то писал название с сайта.

2022-11-23 13:50 UTC, KraPete commented
С `W1-UP`, кстати, просто сделали как получилось. Все названия через пробел, даже `W2 UP` ниже через пробел. А тут вылез тире. Потому я его и заменил.

2022-11-25 06:11 UTC, webconn requested changes
Сходу нашёл ещё несоответствий:

 - синтаксис как попало, где-то `V_OUT`, где-то `5Vout`, нельзя так, если мы это публичным API затеяли
 - в WB7 есть `RTC SCK` (который должен был быть `SCL`, мы ж в I2C)
 - в WB7 есть `Watchdog out`, хотя в WB6 везде `Watchdog input`
 - в WB7 SPI на MOD4 обнозначен `MOD4 SPI MOSI` и т.п., в WB6 `MOD3 MOSI`

Кажется, нам стоит ввести какой-то источник правды об этом, желательно с автоматической проверкой, потому что проморгать тут что-то очень легко

2022-11-25 06:11 UTC, webconn commented on arch/arm/boot/dts/imx6ul-wirenboard61.dts
> +		"MOD1 DE", // 26
А он не должен называться RTS? (аналогично остальные `MODx DE`)

2022-11-25 06:15 UTC, webconn commented
И, кстати, в источнике правды надо не только перечислить имена, но и написать правила их составления (хотя бы в общих чертах) и привести примеры неправильных (как минимум из того, что есть)

2022-11-25 07:21 UTC, KraPete commented on arch/arm/boot/dts/imx6ul-wirenboard61.dts
> +		"MOD1 DE", // 26
Я спросил, где искать, меня послали в документацию на сайте. Там эти пины названы 'DE'.

2022-11-25 07:29 UTC, KraPete commented
> Сходу нашёл ещё несоответствий:
> 
>     * синтаксис как попало, где-то `V_OUT`, где-то `5Vout`, нельзя так, если мы это публичным API затеяли
> 
>     * в WB7 есть `RTC SCK` (который должен был быть `SCL`, мы ж в I2C)
> 
>     * в WB7 есть `Watchdog out`, хотя в WB6 везде `Watchdog input`
> 
>     * в WB7 SPI на MOD4 обнозначен `MOD4 SPI MOSI` и т.п., в WB6 `MOD3 MOSI`
> 
> 
> Кажется, нам стоит ввести какой-то источник правды об этом, желательно с автоматической проверкой, потому что проморгать тут что-то очень легко

1. Так уже было в WB7. Задачи менять названия не стояло. Мне надо их придумать?
2. WB7 я не трогал, задача была "прописать названия для WB6".
3. Ещё раз. Я спросил где названия, меня послали на сайт, там написано `input`.
4. Поправлю

2022-11-25 07:53 UTC, webconn commented
Давай сразу сделаем офигенно, раз уж на то пошло

2022-11-25 08:16 UTC, evgeny-boger commented
>в WB7 есть Watchdog out, хотя в WB6 везде Watchdog input

ну потому что в вб6 кто-то переписывал просто со схемы, а в вб7 я подумал. Ну это же выход с точки зрения вб

>в WB7 есть RTC SCK (который должен был быть SCL, мы ж в I2C)
можно поправить

>С W1-UP, кстати, просто сделали как получилось. Все названия через пробел, даже W2 UP ниже через пробел. А тут вылез тире. Потому я его и заменил.

тогда заменить и там и там


>синтаксис как попало, где-то V_OUT, где-то 5Vout, нельзя так, если мы это публичным API затеяли

оно так по-моему в gpio блоке в интерфейсе уже

2022-11-29 07:08 UTC, KraPete commented
Остались следующие вопросы:
1. Не все названия в верхнем регистре. Надо ли все переводить?
Вот список таких слов
```
Watchdog out
Status
Failsafe
Termination
Pushbutton
Wi-Fi
reserved
Backlight
microSD
eMMC
SoM
```

Можно оставить
```
Wi-Fi
microSD
eMMC
SoM
```
Остальные перевести в верхний регистр

2. Названий с подчёркиваением почти нет, везде тире.
Имеет смысл оставить `V_OUT ON` и `5V_OUT ON` т.к. они уже так написаны в `wb-mqtt-gpio`. Остаётся `SIM_SELECT`. Предалагаю сделать `SIM SELECT`.

2022-11-29 07:12 UTC, webconn commented
> Можно оставить
> 
> ```
> Wi-Fi
> microSD
> eMMC
> SoM
> ```
> 
> Остальные перевести в верхний регистр

Да давай уже все в верхний регистр, `WIFI`, `MICROSD`, `EMMC`, `SOM`, вряд ли кого-то смутит

>     2. Названий с подчёркиваением почти нет, везде тире.
>        Имеет смысл оставить `V_OUT ON` и `5V_OUT ON` т.к. они уже так написаны в `wb-mqtt-gpio`. Остаётся `SIM_SELECT`. Предалагаю сделать `SIM SELECT`.

Мне нравится

2022-11-30 08:38 UTC, webconn commented
По мотивам встречи сегодня: меняем DE обратно на RTS, потому что этим могли пользоваться, все остальные изменения (которые не касаются GPIO для пользователей) можно оставить

2022-12-01 12:55 UTC, webconn reviewed
Давай всё оставшееся в верхний регистр переводить (всякие `Status`, `Watchdog`, `Failsafe`)

2022-12-01 13:11 UTC, KraPete commented
> Давай всё оставшееся в верхний регистр переводить (всякие `Status`, `Watchdog`, `Failsafe`)

Решили же не трогать

2022-12-01 13:15 UTC, webconn commented
Так нет же, мы решили не трогать новые придуманные изменения. Напомню контекст: нам важно было сохранить названия у ножек GPIO, до которых потенциально могли зачем-то дотянуться пользователи. Это касается в первую очередь ножек на модулях расширения (отсюда DE превратился обратно в RTS). GPIO наружу (A1-A4, D1)  уже в порядке, подтяжка 1-Wire по идее используется только у нас внутри, 5Vout и прочие у нас в wb-mqtt-gpio называются через нижнее подчёркивание.

Всё то, что нужно для внутренних нужд, можно менять, не особо опасаясь за совместимость с чьим-то левым софтом, потому там можно сделать всё красиво (а это значит, как мы решили, переводить всё в верхний регистр).

2022-12-05 06:04 UTC, KraPete commented
1. Перевел в верхний регистр "не GPIO".
2. Eth1 RST -> SOM ETH1 RST. Тут не уверен, кажется, что забыли `SOM`?

2022-12-05 06:24 UTC, webconn requested changes

2022-12-05 06:24 UTC, webconn commented on arch/arm/boot/dts/imx6ul-wirenboard65.dts
> +		"Wi-Fi ON", // 10
Тут осталось

2022-12-05 06:24 UTC, webconn commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +		"Wi-Fi ON", // 10
И тут

2022-12-05 06:24 UTC, webconn commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +		"Wi-Fi ON", // 10
И тут

2022-12-05 06:24 UTC, webconn commented on arch/arm/boot/dts/imx6ul-wirenboard690.dts
> +		"Wi-Fi ON", // 10
И тут

2022-12-05 06:24 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard-som-test.dts
> +		"SOM PMIC SCK", "SoM PMIC SDA", "", "", /*  0 - 3 */
```suggestion
		"SOM PMIC SCL", "SoM PMIC SDA", "", "", /*  0 - 3 */
```

2022-12-05 06:24 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard72x.dtsi
> +	override default (or pRESERVED from last boot) register
Упс

2022-12-05 06:24 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard72x.dtsi
> +		"SOM PMIC SCK", "SOM PMIC SDA", "SIM_SELECT", "BUZZER", /*  0 - 3 */
```suggestion
		"SOM PMIC SCL", "SOM PMIC SDA", "SIM_SELECT", "BUZZER", /*  0 - 3 */
```

2022-12-05 06:51 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard72x.dtsi
> +		"USB0 ID", "WATHCDOG OUT", "[NC]", "[NC]", /* 20 - 23 */
```suggestion
		"USB0 ID", "WATCHDOG OUT", "[NC]", "[NC]", /* 20 - 23 */
```

2022-12-05 06:52 UTC, webconn commented
Кажется, это последнее

2022-12-05 06:54 UTC, webconn approved these changes

2022-12-06 16:44 UTC, evgeny-boger approved these changes

2022-12-06 17:42 UTC, vdromanov approved these changes

2022-12-07 05:17 UTC, KraPete commented
Rebase https://github.com/wirenboard/linux/pull/116

2022-12-07 05:17 UTC, closed without merging