wb: Kconfig: add modules for ipsec support
wirenboard/linux pull request #117
Opened 2022-12-07 20:01 UTC by vdromanov

у Гены завёлся l2tp vpn c этим ядром

нам точно такое надо на все wb?

2022-12-08 05:05 UTC, webconn requested changes
Думаю, если эта поддержка не требует кучи места, то почему бы и не добавить везде

2022-12-08 05:05 UTC, webconn commented on arch/arm/configs/wirenboard7_defconfig
> +#ipsec support: https://wiki.strongswan.org/projects/strongswan/wiki/KernelModules
Есть смысл сразу прогнать это через `savedefconfig`, а то в следующий раз будем редактировать файл и эти опции разбегутся

2022-12-08 05:05 UTC, webconn commented on debian/changelog
> +  * wb: Kconfig: add modules for ipsec support
wb7

2022-12-15 20:38 UTC, vdromanov commented on arch/arm/configs/wirenboard7_defconfig
> +#ipsec support: https://wiki.strongswan.org/projects/strongswan/wiki/KernelModules
``make savedefconfig wirenboard7_defconfig`` ни на что не ругается

2022-12-15 20:39 UTC, vdromanov commented on debian/changelog
> +  * wb: Kconfig: add modules for ipsec support
готово

2022-12-16 13:50 UTC, webconn commented on arch/arm/configs/wirenboard7_defconfig
> +#ipsec support: https://wiki.strongswan.org/projects/strongswan/wiki/KernelModules
Это не так делается, `make savedefconfig` сохраняет текущий конфиг в файл `defconfig`, и тебе после этого его надо положить вместо нынешнего.

Примерно так

```console
$ make wirenboard7_defconfig
$ make savedefconfig
$ mv defconfig arch/arm/configs/wirenboard7_defconfig
```

2022-12-16 13:50 UTC, webconn approved these changes

2022-12-19 08:22 UTC, merged