Add wbec files
wirenboard/linux pull request #124
Opened 2023-01-31 17:33 UTC by pgasheev

2023-01-31 22:50 UTC, evgeny-boger reviewed
рекомендую прогнать через scripts/checkpatch.pl чем раньше тем лучше

2023-01-31 22:50 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +enum wbec_iio_channel_regs {
я такого не видел в драйверах других, обычно просто `#define`

2023-01-31 22:50 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +    WBEC_IIO_CHANNEL(V_A1, IIO_VOLTAGE, BIT(IIO_CHAN_INFO_PROCESSED), "v_a1"),
`v_` не надо, `A1` и прочее я бы сделал в верхнем регистре, максимально похоже на клеммники

2023-01-31 22:50 UTC, evgeny-boger commented on drivers/input/misc/pwrkey-wbec.c
> +	err = devm_request_any_context_irq(&pwr->dev, fall_irq,
получается IRQ только для pwrkey? Наверное логичнее его сразу на уровне mfd делать

2023-01-31 22:50 UTC, evgeny-boger commented on drivers/rtc/rtc-wbec.c
> +	tm->tm_sec = bcd2bin(regs[0] & 0x7F);
а нам оно надо в BCD хранить? Чем это удобнее?

Я понимаю, что для RTC - это традиция. Но меня это всегда страшно бесило в новых чипах.

2023-01-31 22:50 UTC, evgeny-boger commented
на первый взгляд всё хорошо

2023-02-01 07:17 UTC, pgasheev commented on drivers/iio/adc/iio-wbec.c
> +enum wbec_iio_channel_regs {
Отсюда https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/iio/adc/da9150-gpadc.c#L24
Но да, в других чаще дефайны просто. Переделаю

2023-02-01 07:19 UTC, pgasheev commented on drivers/rtc/rtc-wbec.c
> +	tm->tm_sec = bcd2bin(regs[0] & 0x7F);
На стороне линукса ничем не удобнее, переделаю тогда. Перенесу эту конверсию в МК

2023-02-21 17:31 UTC, pgasheev commented
Кажется это весь комплект драйверов. Все работают. watchdog еще не до конца, там приберусь. Добавил внешние прерывания, т.к. без этого не хотел работать RTC alarm, а точнее утилита hwclock: она проверяет ход часов и работу будильника и без прерывания зависает. Линию INT на схеме предусмотрели

2023-02-21 17:33 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	.base = 0x400,	// TODO must be -1
Вот этот вопрос для меня остается непонятным. Везде пишут что должно быть -1, но так не работает, пишет что не может найти свободный range. В наших оверлеях передается какое-то число, которое заранее рассчитывается, чтоб не пересекалось с другими gpio, если я правильно понимаю.

Как тут нужно сделать правильно, не могу понять

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	.base = 0x400,	// TODO must be -1
должен быть -1

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	struct wbec_gpio_info *gpio;
название переменной мне не нравится. Лучше info или drvdata или data или что-то такое.

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	gpio->wbec = dev_get_drvdata(pdev->dev.parent);
тут не надо ошибки проверить? Наверное же кто-то может попробовать напрямую в DT пропсиать wbec-gpio и тут всё сломается

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	gpio->gpio_chip = wbec_gpio_chip;
а так можно? Я в паре соседних мест посмотрел, там создаётся копия структуры. А у тебя прямо структура готовая статическая передаётся сюда, а она же одинаковая для всех экземпляров будет

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +// SPDX-License-Identifier: GPL-2.0-only
а чем нам кстати не подошёл какой-то generic драйвер через regmap?

Я про gpio-regmap.c

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	WBEC_GPIO_V_OUT,
нам обязательно это кодить? Нельзя в DT вынести? Ну явно же в следующем WB будет на один больше или меньше входов, или они переименуются.
В общем не нравится мне это.

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_USB_CONSOLE,
1) для напряжения на USB есть устоявшееся название VBUS.
2) опять же: нельзя драйвер более generic, а описания - в DT?

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +	return iio_device_register(indio_dev);
лучше devm_iio_device_register и тогда не надо в remove ничего делать.

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/mfd/wbec.c
> +	dev_err(&wbec_i2c_client->dev, "Device not actually shutdown. Check EC and FETs!\n");
а в других power off драйверах так же? просто dev_err и всё?

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/mfd/wbec.c
> +	wbec->regmap_cfg_8 = &wbec_regmap_config_8;
а нам точно вообще два регмапа надо? Может всё на 16 бит сделать?

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/mfd/wbec.c
> +static void wbec_pm_power_off(void)
ещё нужно restart_handler сделать и зарегистрировать, чтобы он по reboot дёргался. Потому что сейчас reboot делается через AXP

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/mfd/wbec.c
> +	wbec_i2c_client = client;
чот коряво. Может просто ссылку на один экземпляр самого struct wbec сохранять?

Ну и я понимаю, что у нас сейчас этот WBEC один будет. Но драйвера хорошо бы писать, чтобы они от количества устройств не зависели. А здесь после remove() произойдёт печальное.

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/mfd/wbec.c
> +		ret = regmap_add_irq_chip(wbec->regmap_8, client->irq,
devm_regmap_add_irq_chip

2023-02-28 16:51 UTC, evgeny-boger commented on drivers/mfd/wbec.c
> +	{ .compatible = "wbec" },
wirenboard,wbec же должно быть?

2023-02-28 16:52 UTC, evgeny-boger commented
По RTC IRQ - а в ядре нет драйверов без аппаратного прерывания, точно? Наш PCF85063 например, он разве с прерыванием подключен?

2023-02-28 17:13 UTC, pgasheev commented
> По RTC IRQ - а в ядре нет драйверов без аппаратного прерывания, точно? Наш PCF85063 например, он разве с прерыванием подключен?

Без прерывания, но там и alarm не задействован.
https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/rtc/rtc-pcf85063.c#L591
То есть если irq не заводить, то alarm на PCF85063 работать не будет

2023-02-28 17:22 UTC, pgasheev commented on drivers/mfd/wbec.c
> +	dev_err(&wbec_i2c_client->dev, "Device not actually shutdown. Check EC and FETs!\n");
Кажется да
https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/mfd/rk808.c#L474
https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/mfd/axp20x.c#L822

2023-02-28 17:27 UTC, pgasheev commented on drivers/mfd/wbec.c
> +	wbec_i2c_client = client;
Конкретно в случае с pm_power_off не получится использовать несколько драйверов, и оттуда не получить данные драйвера. Поэтому просто сохраняется указатель на клиента (переделаю на struct wbec) и используется в колбэке pm_power_off.

В других драйверах видел что в DT прописывают свойство типа `rockchip,system-power-controller` и забирают pm_power_off только если оно true. Тут можно сделать так же

2023-02-28 17:29 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +// SPDX-License-Identifier: GPL-2.0-only
Я его поздно увидел, посмотрю, вроде должен подойти

2023-02-28 18:27 UTC, evgeny-boger commented
> > По RTC IRQ - а в ядре нет драйверов без аппаратного прерывания, точно? Наш PCF85063 например, он разве с прерыванием подключен?
> 
> Без прерывания, но там и alarm не задействован. https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/rtc/rtc-pcf85063.c#L591 То есть если irq не заводить, то alarm на PCF85063 работать не будет

А нам нужен alarm? У нас же про пробуждение из выключенного состояние.

2023-02-28 18:28 UTC, evgeny-boger commented on drivers/mfd/wbec.c
> +	wbec_i2c_client = client;
я про wbec_i2c_client

2023-02-28 19:02 UTC, pgasheev commented
> > > По RTC IRQ - а в ядре нет драйверов без аппаратного прерывания, точно? Наш PCF85063 например, он разве с прерыванием подключен?
> > 
> > 
> > Без прерывания, но там и alarm не задействован. https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/rtc/rtc-pcf85063.c#L591 То есть если irq не заводить, то alarm на PCF85063 работать не будет
> 
> А нам нужен alarm? У нас же про пробуждение из выключенного состояния. Ну и это не через прерывание делается. Так что странно.

Не знаю, может я не до конца разобрался, но как тогда alarm на пробуждение установить? 
Я делаю так: `rtcwake -m off -d rtc2 <time>`. Оно дергает функции драйвера `set_alarm` и выключается. Эта штука работает и без прерываний.

Но есть ещё утилита hwclock, которая кажется тоже должна работать с нашим wbec. И она не просто читает время, а проверяет всё, и ход часов (поллит 1 секунду) и работу будильника (заводит на пару секунд вперед), а там уже нужны прерывания, без них она ошибку выдает

2023-03-01 08:05 UTC, evgeny-boger commented
> > > > По RTC IRQ - а в ядре нет драйверов без аппаратного прерывания, точно? Наш PCF85063 например, он разве с прерыванием подключен?
> > > 
> > > 
> > > Без прерывания, но там и alarm не задействован. https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/rtc/rtc-pcf85063.c#L591 То есть если irq не заводить, то alarm на PCF85063 работать не будет
> > 
> > 
> > А нам нужен alarm? У нас же про пробуждение из выключенного состояния. Ну и это не через прерывание делается. Так что странно.
> 
> Не знаю, может я не до конца разобрался, но как тогда alarm на пробуждение установить? Я делаю так: `rtcwake -m off -d rtc2 <time>`. Оно дергает функции драйвера `set_alarm` и выключается. Эта штука работает и без прерываний.
> 
> Но есть ещё утилита hwclock, которая кажется тоже должна работать с нашим wbec. И она не просто читает время, а проверяет всё, и ход часов (поллит 1 секунду) и работу будильника (заводит на пару секунд вперед), а там уже нужны прерывания, без них она ошибку выдает

Ну можно сэмулировать это через hrtimer пока. Ну просто прерывание же должно обрабатываться в самом wbec, потом только его дочерние толжны в rtc идти, а сейчас у нас костыль получается. Можно конечно сразу сделать хорошо прерывание, но мы по-моему даже не решили, нужно ли оно нам.

2023-03-01 08:08 UTC, evgeny-boger commented
я ещё подумал, что hwclock на самом деле ничего не "проверяет". Она просто пытается поставить системное время с гранулярностью точнее, чем секунда. Для этого запрашивается alarm по границе секунды с rtc и ровно по нему ставится время. Так получается точность синхронизации не в +/- 1 секунда, а с точностью до latency прерывания + юзерспейса. 

Ну вот кажется то же самое можно обеспечить и без аппартной ноги прерывания, просто на уровне драйвера rtc. Там кстати в интерфейсе ядерном с точностью до секунды всё?

2023-03-01 13:32 UTC, pgasheev commented
> Ну просто прерывание же должно обрабатываться в самом wbec, потом только его дочерние толжны в rtc идти, а сейчас у нас костыль получается.

Сейчас так и есть ведь. В `wbec.c` есть `regmap_irq_chip`, который и читает флаги из wbec, когда прилетает прерывание по линии INT. Потом дергает дочерние.
Мне кажется наоборот, с hrtimer костыльно выглядит. Ты имеешь в виду поллить через hrtimer флаг прерывания в rtc драйвере?

> я ещё подумал, что hwclock на самом деле ничего не "проверяет"

Если её запустить без параметров, то там по дефолту `--show`, то есть просто читает дату время и показывает. Но при этом проверяет что часы идут и будильник работает. То есть если в драйвере поставить заглушку, которая будет вместо времени выдавать константы, hwclock такое не переварит. Если есть alarm, она пытается его завести и ожидает сработки. Если не срабатывает - тоже ошибку выдает. Вот это вроде и не нужно, но всё равно должно нормально работать я думаю?

> Там кстати в интерфейсе ядерном с точностью до секунды всё?

Да

2023-03-01 17:20 UTC, evgeny-boger commented
Да я просто пока не хочу особо завязываться на INT, пока он не понадобился в действительно важных вещах.

А вот это не то, что нам надо:

```
config RTC_INTF_DEV_UIE_EMUL
	bool "RTC UIE emulation on dev interface"
	depends on RTC_INTF_DEV
	help
	  Provides an emulation for RTC_UIE if the underlying rtc chip
	  driver does not expose RTC_UIE ioctls. Those requests generate
	  once-per-second update interrupts, used for synchronization.

	  The emulation code will read the time from the hardware
	  clock several times per second, please enable this option
	  only if you know that you really need it.


```

2023-03-01 17:23 UTC, evgeny-boger commented
Или просто поставить `uie_unsupported=1` для драйвера. 

Я просто открыл исходник hwclock и rtc/dev и посмотрел кто и что там дёргает.

2023-03-03 09:04 UTC, nikitoz236 commented on drivers/mfd/wbec.c
> +		.of_match_table = of_match_ptr(wbec_of_match),
кудато наверное нужно прописать ARRAY_SIZE() ?? или это делает of_match_ptr() ?

2023-03-03 09:04 UTC, nikitoz236 commented on drivers/rtc/rtc-wbec.c
> +	rtc_update_irq(wbec_rtc->rtc, 1, RTC_IRQF | RTC_AF);
возвразщает чтото может ? вдруг не всегда можно возвращать IRQ_HANDLED

2023-03-10 07:30 UTC, pgasheev commented on drivers/rtc/rtc-wbec.c
> +	rtc_update_irq(wbec_rtc->rtc, 1, RTC_IRQF | RTC_AF);
rtc_update_irq тип void, в других драйверах аналогично

2023-03-10 08:20 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	WBEC_GPIO_V_OUT,
Это уберу, вынесу в DT

2023-03-10 08:29 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +// SPDX-License-Identifier: GPL-2.0-only
Посмотрел на gpio-regmap, в принципе подходит, только нюанс с направлениями input/output. У нас они не задаются, при этом часть input, часть output, через gpio-regmap такое не сделать, там все будут input/output. Но наверно можно на это забить и input/output определить уровнем выше

2023-03-10 08:33 UTC, pgasheev commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_USB_CONSOLE,
Не нашел штатного способа вынести описания в DT, как например с `gpio-line-names`. Как вариант делать свои свойства и в probe доставать их из DT?

Кстати сейчас из EC передаются итоговые мВ для напряжения. Не надо передавать raw (или мВ после делителя), а делители пересчитывать уже в линуксе?

2023-03-12 09:06 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +// SPDX-License-Identifier: GPL-2.0-only
а отдельный драйвер вообще нужен?

2023-03-17 08:41 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +// SPDX-License-Identifier: GPL-2.0-only
gpio-regmap это не драйвер, это что-то типа хэлперов. Там нет `probe`. Поэтому нужен, получается. В нашем ядре я нашел только 1 драйвер, который использует gpio-regmap, `gpio-sl28cpld.c`

2023-03-17 08:41 UTC, pgasheev commented on drivers/mfd/wbec.c
> +	wbec->regmap_cfg_8 = &wbec_regmap_config_8;
Переделал всё на 16 бит

2023-03-17 08:43 UTC, pgasheev commented on drivers/mfd/wbec.c
> +		.of_match_table = of_match_ptr(wbec_of_match),
Там gpio-sl28cpld.c кончается пустым элементом, отдельного поля для размера нет

2023-03-17 09:53 UTC, pgasheev commented on drivers/gpio/gpiolib.c
> +		base = gdev->base + gdev->ngpio;
Это отсюда https://github.com/torvalds/linux/commit/7b61212f2a07a5afd213c8876e52b5c9946441e2

Я не знаю, насколько это правильно, но оно у меня никак не работало, если в base передавать -1. И тут есть какие-то изменения от нас https://github.com/wirenboard/linux/commit/1e1b35971a62853374b94031a60c4cddc8823e7a
И `ARCH_NR_GPIOS_DYNALLOC=256`, что меньше чем число GPIO на A40i и из-за этого он и не может найти свободный range, если я правильно понимаю

2023-03-17 10:43 UTC, evgeny-boger commented on drivers/gpio/gpiolib.c
> +		base = gdev->base + gdev->ngpio;
этот коммит последний раз был нужен на WB4. Я думаю можно убрать и всё.

2023-03-17 13:32 UTC, pgasheev commented on drivers/gpio/gpiolib.c
> +		base = gdev->base + gdev->ngpio;
Да, откатил, работает. Только номера он назначает с конца,

```
gpiochip0: GPIOs 0-287, parent: platform/1c20800.pinctrl, 1c20800.pinctrl:
 gpio-0   (SOM ETH1 RXD3       )
 gpio-1   (SOM ETH1 RXD2       )
....
 gpio-286 (                    )
 gpio-287 (                    )

gpiochip1: GPIOs 411-415, parent: spi/spi0.0, spi0.0, can sleep:
 gpio-411 (WBEC A1             )
 gpio-412 (WBEC A2             )
 gpio-413 (WBEC A3             )
 gpio-414 (WBEC A4             )
 gpio-415 (WBEC V OUT          )
```

https://github.com/wirenboard/linux/blob/dev/v5.10.y/arch/arm/Kconfig#L1362

Оставляем так? wd-14 начинаются с 0x200 и выше, вроде конфликтовать не должно

2023-03-30 08:44 UTC, evgeny-boger commented on drivers/gpio/gpiolib.c
> +		base = gdev->base + gdev->ngpio;
вот интересный вопрос на самом деле: делать тут всё-таки стабильные номера или нет. С одной стороны, куча клиентов до сих пор работает через sysfs. С другой - это плохо.

2023-03-30 08:45 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_USB_CONSOLE,
тут хорошо бы понять позицию мейнтейнеров iio по поводу описания в DT. Может имеет смысл список рассылки почитать, или явно написать письмо мейнтейнеру и спросить. Некоторые не любят.

2023-03-30 09:48 UTC, webconn commented on drivers/mfd/wbec.c
> +	msleep(500);
Разные задержки тут и выше, это специально так или надо сделать константу?

2023-03-30 09:48 UTC, webconn commented on drivers/rtc/Makefile
> +obj-$(CONFIG_RTC_DRV_WBEC)		+= rtc-wbec.o
```suggestion
obj-$(CONFIG_RTC_DRV_WBEC)	+= rtc-wbec.o
```

2023-03-30 09:48 UTC, webconn commented on drivers/rtc/rtc-wbec.c
> +	regs[2] = (tm->tm_mon + 1) << 8;
Кажется, тут только что потеряли день недели
```suggestion
	regs[2] |= (tm->tm_mon + 1) << 8;
```

2023-03-30 09:48 UTC, webconn commented on drivers/input/misc/pwrkey-wbec.c
> +		dev_info(&pwr->dev, "Power key press detected\n");
Не уверен, что это debug, кстати. Будет хорошо, если такие сообщения будут в dmesg

2023-03-30 09:48 UTC, webconn commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_USB_CONSOLE,
> Не нашел штатного способа вынести описания в DT, как например с gpio-line-names. Как вариант делать свои свойства и в probe доставать их из DT?

Тут вроде описаны примеры: https://www.kernel.org/doc/Documentation/devicetree/bindings/iio/iio-bindings.txt

```
        adc: max1139@35 {
		compatible = "maxim,max1139";
		reg = <0x35>;
		#io-channel-cells = <1>;
	};

	...

	iio-hwmon {
		compatible = "iio-hwmon";
		io-channels = <&adc 0>, <&adc 1>, <&adc 2>,
			<&adc 3>, <&adc 4>, <&adc 5>,
			<&adc 6>, <&adc 7>, <&adc 8>,
			<&adc 9>;
	};

	some_consumer {
		compatible = "some-consumer";
		io-channels = <&adc 10>, <&adc 11>;
		io-channel-names = "adc1", "adc2";
	};
```

2023-03-30 09:52 UTC, webconn requested changes
1. `sed 's/Wirenboard/Wiren Board/g`
2. Куча todo про `remove debug`, может, поменять на `dev_dbg`?
3. Вообще пройтись по TODO, там от отсутствующих описаний в комментах до `TODO Check power loss?` в RTC
4. Про вынос описаний iio в dts оставил [коммент](https://github.com/wirenboard/linux/pull/124#discussion_r1153012670)

Я тут ещё хотел спросить (может, исходники читаю невнимательно), а мы какой-нибудь пин для прерывания с wbec не вывели что ли?

Я тут ещё хотел спросить, может, просто из исходников не понимаю: а мы

2023-03-30 10:13 UTC, pgasheev commented
> Я тут ещё хотел спросить (может, исходники читаю невнимательно), а мы какой-нибудь пин для прерывания с wbec не вывели что ли?

Пин есть, но прямо сейчас не используется. Я реализовывал работу с ним через `regmap_irq_chip`, но в итоге решили пока отказаться, т.к. нужен он только для pwrkey. Там сделал периодическую задачу на опрос флага прерывания в EC

2023-03-30 10:16 UTC, pgasheev commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_USB_CONSOLE,
Это понятно, но примере тут внутри драйвера max1139 всё равно есть захардкоженные каналы. А Женя предлагает их вынести в DT, чтобы если что-то в прошивке EC изменится, драйвер не менять а только DT поправить

2023-03-30 10:24 UTC, pgasheev commented on drivers/mfd/wbec.c
> +	msleep(500);
Не специально, вынесу в константу

2023-03-30 11:10 UTC, pgasheev commented
> sed 's/Wirenboard/Wiren Board/g

Заменить `Wirenboard` на `Wiren Board`? Но я не не нашёл, где ты увидел?

2023-04-12 18:41 UTC, evgeny-boger commented on drivers/gpio/gpiolib.c
> +		base = gdev->base + gdev->ngpio;
давай всё-таки сделаем возможность указывать base через DT, чтобы сделать фиксированные номера этих GPIO во всех будущих железках.

2023-04-13 06:20 UTC, pgasheev commented on drivers/gpio/gpiolib.c
> +		base = gdev->base + gdev->ngpio;
Ок, только тогда gpio-regmap драйвер уже не походит, там нет возможности задать base снаружи. И либо его править, либо писать свой (он уже был сделан вначале, откачу). Я думаю, второй вариант

2023-07-10 23:19 UTC, evgeny-boger requested changes
так нехорошо делать. Если есть патч в апстриме, то надо его через cherry-pick сделать, желательно отдельным PR

2023-07-10 23:40 UTC, evgeny-boger requested changes

2023-07-10 23:40 UTC, evgeny-boger commented on Documentation/devicetree/bindings/mfd/wbec.txt
> +Wiren Board Embedded Controller
документацию на DT надо делать в yaml, в txt только старая. И проверять через make dt_schema_check или что-то такое

2023-07-10 23:40 UTC, evgeny-boger commented on Documentation/devicetree/bindings/mfd/wbec.txt
> +- wakeup-source:  Set for ability to power off and wakeup with alarm
а они точно optional?

2023-07-10 23:40 UTC, evgeny-boger commented on Documentation/devicetree/bindings/vendor-prefixes.yaml
> +    description: Wiren Board LLC
`Wiren Board, LLC`

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/Makefile
> +	sun8i-r40-wirenboard740.dtb \
в продакшн пойдёт уже 7.4.1, давай переименуем

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +#include "sun8i-r40-wirenboard73x.dtsi"
ой, нет, плохая идея. Тут полфайла поменялась.
Никаких переопределений кусков нод и удаления нод не должно быть.
Или копировать, или делать какой-то инклюд только с абсолютно одинаковыми кусками.

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +	compatible = "wirenboard,wirenboard-740", "wirenboard,wirenboard-720", "wirenboard,wirenboard-700", "allwinner,sun8i-r40";
сломал compatible? Кажется, у нас в остальных уже были 73x, 7xx и т.п. 
Здесь так же надо добавить.

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +	pinctrl_wbec_i2c_gpio: wbec-i2c-pb-pins {
многовато ног для i2c

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +		compatible = "whwave,sd3078";	// TODO compatible with SD3178 ???
что с туду?

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +/** TODO
что с этим?

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +			<&spi2_cs0_pb_pin>;
форматирование поехало

2023-07-10 23:40 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40.dtsi
> +			/omit-if-no-ref/
не хочу коммитить в r40.dtsi без нужды: мешает мерджить изменения из апстрима.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/Kconfig
> +	tristate "Wirenboard Embedded Controller GPIO"
коряво написано, и Wiren Board с ошибкой

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/Kconfig
> +	  This driver supports Wirenboard Embedded Controller GPIO
надо подробьнее написать, и Wiren Board с ошибкой

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +/* generic gpio chip */
не понял комментарий

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	dev_dbg(wbec_gpio->dev, "%s function. offset=%u\n", __func__, offset);
странное дебаг сообщение.Если нужно - переписать, если ненужно - удалить

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +		dev_err(wbec_gpio->dev, "error when read gpio %u\n", offset);
корявый английский

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	return !!(val & mask);
раздражают меня эти `!!`. Мне кажется `val & mask ? 1 : 0` выглядит лучше.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	dev_dbg(wbec_gpio->dev, "%s function. offset=%u, value=%d\n", __func__, offset, value);
сообщение, см выше

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	reg = WBEC_REG_GPIO + (offset / wbec_gpio->gpio_per_reg);
gpio_per_reg не может быть не заполнено в этом месте?

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	reg = WBEC_REG_GPIO + (offset / wbec_gpio->gpio_per_reg);
не нужен хелпер или что-то такое, чтобы считать offset и mask? Копипаста с предыдущей фунцией.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "ngpios", &ngpios);
а зачем это?

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "linux,base", &base);
linux,base точно не обрабатывается в gpio core выше?

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "gpio-per-reg", &wbec_gpio->gpio_per_reg);
а это зачем?

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/gpio/gpiolib.c
> +	int base = ARCH_NR_GPIOS - ngpio;
чот странное, зачем оно в этом PR?
Если останется, то нужно сделать отдельным коммитом.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/iio/adc/Kconfig
> +	tristate "Wirenboard Embedded Controller GPIO Industrial I/O"
https://github.com/wirenboard/brand

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/iio/adc/Kconfig
> +	tristate "Wirenboard Embedded Controller GPIO Industrial I/O"
описание на английском корявое.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/iio/adc/Makefile
> +obj-$(CONFIG_WBEC_IIO) += iio-wbec.o
файл называется как-то не так, как соседние. Это точно нормально?

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_A1,
я очень хочу здесь поделить аналоговые входы на
1) те, которые обрабатывается прошивкой WBEC. Типа V_in и т.п. 
2) и те, которые не обрабатываются и никогда не будут, типа A1-A4

Для последних мне не хотелось бы иметь каких-то специальных названий внутри, потому что это может нам очень осложнить жизнь в будущем. К тому же, они особо нигде и не используются.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +	dev_dbg(&indio_dev->dev, "%s function. addr=0x%lX\n", __func__, channel->address);
здесь, как и везде, странный дебаг.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +	case IIO_CHAN_INFO_RAW:
не нравнится мне, как это всё написано. Функции read/store в iio, конечно, совершенно безумные, и эти switch/case везде плохо читаются. Но здесь оно плохо. Можно лучше.
Я бы предложил в этой функции иметь абсолютный минимум логики и дёргать другие функции, с понятными названиями.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +		return IIO_VAL_INT_PLUS_MICRO;
кажется, если множитель 1, то не должно быть INT_PLUS_MICO, а должно быть просто INT или что-то такое.
Для множителя 10 по-моему тоже PLUS_MICRO многовато.

И да, повторю коммент выше: ничерта тут непонятно чей scale где. Надо разбивать на разные функции.

2023-07-10 23:40 UTC, evgeny-boger commented on drivers/input/misc/Kconfig
> +	  Say Y to enable support of onkey embedded into WBEC. onkey
onkey? Никогда такого слова не видел.
Проверь английский.

2023-07-11 07:21 UTC, pgasheev commented
> spi автосаспенд: так нехорошо делать. Если есть патч в апстриме, то надо его через cherry-pick сделать, желательно отдельным PR

https://github.com/wirenboard/linux/pull/139

2023-07-11 07:26 UTC, pgasheev commented on drivers/gpio/gpiolib.c
> +	int base = ARCH_NR_GPIOS - ngpio;
Обсуждения тут: https://github.com/wirenboard/linux/pull/124#discussion_r1140018350
Это откат нашего коммита https://github.com/wirenboard/linux/commit/1e1b35971a62853374b94031a60c4cddc8823e7a
Отдельным PR сделать?

2023-07-11 08:38 UTC, pgasheev commented on drivers/input/misc/Kconfig
> +	  Say Y to enable support of onkey embedded into WBEC. onkey
Прямо в этом файле onkey почти везде в описаниях, заменю на power button

2023-07-11 08:59 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "linux,base", &base);
Кажется это чисто наша история, больше в ядре этого нигде нет
63d8deaafaa27e25bb457bf6289429809c78fc82
(я ещё тут с названием ошибся, исправлю)

2023-07-11 09:19 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "gpio-per-reg", &wbec_gpio->gpio_per_reg);
Чтобы можно было через DT переопределить и не править драйвер. Хотя конечно вряд ли получится изменить размер регистра безболезненно для других драйверов, поэтому можно убрать

2023-07-11 10:01 UTC, webconn commented
> > sed 's/Wirenboard/Wiren Board/g
> 
> Заменить `Wirenboard` на `Wiren Board`? Но я не не нашёл, где ты увидел?

Где-то я вроде это встречал в нескольких местах, сейчас не вижу

2023-07-11 10:06 UTC, webconn reviewed
Вроде в остальном нормально

2023-07-11 10:06 UTC, webconn commented on drivers/mfd/wbec.c
> +	 * pm_power_off may points to a function from another module.
```suggestion
	 * pm_power_off may point to a function from another module.
```

2023-07-12 00:09 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "linux,base", &base);
это точно было (посмотри гугол), видимо везде из ядра уже выпилили. Давай тоже выпилим значит.

2023-07-12 00:09 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "gpio-per-reg", &wbec_gpio->gpio_per_reg);
да, давай

2023-07-12 00:09 UTC, evgeny-boger commented on drivers/gpio/gpiolib.c
> +	int base = ARCH_NR_GPIOS - ngpio;
отдельным, да

2023-07-12 00:10 UTC, evgeny-boger commented on drivers/input/misc/Kconfig
> +	  Say Y to enable support of onkey embedded into WBEC. onkey
ну если везде и в интернетах встречается, то ок

2023-07-12 06:06 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "linux,base", &base);
В гугле нашел в ядре v3.
А как выпилим? Кажется обсуждение по кругу пошло. У нас же это в hwconf используется для боковых модулей, то есть совсем выпилить не получится.
Конкретно здесь - можно, тогда будет так: https://github.com/wirenboard/linux/pull/124#discussion_r1140243496

2023-07-12 07:24 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "ngpios", &ngpios);
Чтобы через DT задать число гпио без изменения драйвера. Используется и в других драйверах, например https://github.com/wirenboard/linux/blob/dev/v5.10.y/drivers/gpio/gpio-rda.c#L213

2023-07-12 08:09 UTC, pgasheev commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +		compatible = "whwave,sd3078";	// TODO compatible with SD3178 ???
Проверено, работает, TODO убрал

2023-07-12 08:09 UTC, pgasheev commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +/** TODO
Проверено, работает, TODO убрал

2023-07-12 08:31 UTC, pgasheev commented on drivers/gpio/gpiolib.c
> +	int base = ARCH_NR_GPIOS - ngpio;
https://github.com/wirenboard/linux/pull/140

2023-07-12 10:59 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +/* generic gpio chip */
Что-то старое осталось, убрал

2023-07-12 11:43 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	dev_dbg(wbec_gpio->dev, "%s function. offset=%u\n", __func__, offset);
Убрал

2023-07-12 12:11 UTC, pgasheev commented on drivers/iio/adc/iio-wbec.c
> +	dev_dbg(&indio_dev->dev, "%s function. addr=0x%lX\n", __func__, channel->address);
Подобный дебаг везде выпилил

2023-07-12 14:10 UTC, pgasheev commented on drivers/iio/adc/Makefile
> +obj-$(CONFIG_WBEC_IIO) += iio-wbec.o
Наверно не очень нормально. У нас тут получилась смесь ADC и TEMP и я назвал iio.

Может надо сделать два отдельных драйвера, `iio/adc/wbec_adc.c` и `iio/temperature/wbec_temp.c`? 
Или просто назвать файл как соседние, `wbec_adc.c`?

2023-07-12 14:12 UTC, pgasheev commented on drivers/iio/adc/Makefile
> +obj-$(CONFIG_WBEC_IIO) += iio-wbec.o
Смотрю что в соседних драйверах тоже встречается смесь разного и они лежат в папке adc и называются `_adc`. Так что я просто переименую тогда

2023-07-12 21:33 UTC, evgeny-boger commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "linux,base", &base);
да, я про здесь. Давай выпилим, я передумал.

2023-07-13 06:21 UTC, pgasheev commented on drivers/gpio/gpio-wbec.c
> +	ret = device_property_read_u32(&pdev->dev, "linux,base", &base);
Выпилил, вернул gpio-regmap драйвер

2023-07-14 07:36 UTC, pgasheev commented on drivers/iio/adc/iio-wbec.c
> +		return IIO_VAL_INT_PLUS_MICRO;
Да, тут можно множитель просто INT. Заменил

2023-07-14 07:48 UTC, pgasheev commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_A1,
Вот тут я не знаю как лучше сделать.
В голову приходит в DTS определить что-то такое:
```
wirenboard,wbec-adc-general-ch-address = <0x43>, <0x44>, <0x45>, <0x46>
wirenboard,wbec-adc-general-ch-names = "A1", "A2", "A3", "A4"
```

В драйвере иметь `const struct iio_chan_spec` с описанием каналов с напряжениями. Потом в probe выделять память под массив `struct iio_chan_spec` размером в сумму каналов захардкоженных и определенных через DT и заполнять там.
Тогда постоянные каналы будут иметь номера от 0 до N, каналы, определенные через DT будут начинаться с N-1

2023-07-14 08:06 UTC, evgeny-boger commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_A1,
ну а так хоть в одном драйвере делали?

Не, я думал просто назвать внутри эти каналы как, не знаю, ADC1-ADC6, промаркировать их так же на схеме и всё.

А для совместимости юзерспейса мы же всё равно делаем повторялку iio с названиями a1_volt и т.п. Вот там этот маппинг и появится.

2023-07-14 08:13 UTC, pgasheev commented on drivers/iio/adc/iio-wbec.c
> +	WBEC_IIO_CH_V_A1,
Я не нашел, чтобы так делали в других драйверах. Там же микросхемы, у которых каналов больше или меньше быть не может. А у нас с обновлением прошивки - может.

Тогда я назову как ты предлагаешь и прошивке их перемещу в конец диапазона, а то сейчас они не очень удачно в середине и расширить не получится. Увеличу число каналов до 6

2023-07-14 08:39 UTC, pgasheev commented on Documentation/devicetree/bindings/mfd/wbec.txt
> +Wiren Board Embedded Controller
Готово

2023-07-14 08:40 UTC, pgasheev commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +#include "sun8i-r40-wirenboard73x.dtsi"
Готово. Скопировал

2023-07-17 05:40 UTC, webconn commented on drivers/iio/adc/wbec_adc.c
Остальные исходники вроде лежат в файлах вида `func-wbec.c`, не единообразненько получилось, может, переименуем этот?

2023-07-17 05:40 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +	compatible = "wirenboard,wirenboard-741", "wirenboard,wirenboard-740", "wirenboard,wirenboard-74x", "wirenboard,wirenboard-72x", "wirenboard,wirenboard-720", "wirenboard,wirenboard-700", "wirenboard
Тут ещё бы `wirenboard,wirenboard-73x`

2023-07-17 05:40 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard74x.dtsi
> +			   there is seemingly no way to assiciate iio channel index (N
```suggestion
			   there is seemingly no way to associate iio channel index (N
```

2023-07-17 05:40 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard74x.dtsi
> +			>;
Выравнивание поехало, кажется

2023-07-17 05:40 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard74x.dtsi
> +		reg = <0x32>;
```suggestion
		reg = <0x32>;
		status = "disabled";
```

Я точно не знаю, так было бы явно показано, что эта штука дополнительно включается

2023-07-17 06:21 UTC, pgasheev commented on drivers/iio/adc/wbec_adc.c
Согласен, но с другой стороны, файлики в папке `iio/adc` чаще называются `xxx_adc.c` или не содержать adc в названии совсем. Я переименую

2023-07-17 06:25 UTC, pgasheev commented on arch/arm/boot/dts/sun8i-r40-wirenboard740.dts
> +	compatible = "wirenboard,wirenboard-741", "wirenboard,wirenboard-740", "wirenboard,wirenboard-74x", "wirenboard,wirenboard-72x", "wirenboard,wirenboard-720", "wirenboard,wirenboard-700", "wirenboard
Добавил

2023-07-17 06:29 UTC, pgasheev commented on arch/arm/boot/dts/sun8i-r40-wirenboard74x.dtsi
> +			>;
Поправил

2023-07-17 06:58 UTC, pgasheev commented on arch/arm/boot/dts/sun8i-r40-wirenboard74x.dtsi
> +		reg = <0x32>;
Да, это обсуждали, сделал

2023-07-18 18:33 UTC, evgeny-boger commented on Documentation/devicetree/bindings/mfd/wirenboard,wbec.yaml
> +        vin: wbec-power@0 {
тут не очень логично получается. Думаю нужна отдельная запись в /sys/class/power_supply  именно для состояния входного питания

2023-07-21 07:14 UTC, pgasheev commented on Documentation/devicetree/bindings/mfd/wirenboard,wbec.yaml
> +        vin: wbec-power@0 {
А она есть, `/sys/class/power_supply/wbec-power/online`
Или что ты имеешь в виду?

2023-08-10 07:25 UTC, webconn commented
А этот pr не пора закрывать из-за https://github.com/wirenboard/linux/pull/142?

2023-08-10 07:30 UTC, pgasheev commented
> А этот pr не пора закрывать из-за #142?

Я думаю сначала тут получить аппрув, потом #142 привести в соответствие (немного отстал он уже) и его влить. #142 тоже нужно посмотреть на предмет разбиения по коммитам

2023-08-11 11:27 UTC, pgasheev commented
Давайте это правда закроем и продолжим тут. Я ветки в соответствие привел #142 
@evgeny-boger @webconn

2023-08-11 20:51 UTC, closed without merging