Feature/wb7min
wirenboard/linux pull request #125
Opened 2023-02-05 18:32 UTC by evgeny-boger

2023-02-08 12:37 UTC, webconn commented
А можешь дать описание того, что ты делаешь? (у нас так по процессам положено)

2023-02-08 12:47 UTC, webconn requested changes

2023-02-08 12:47 UTC, webconn commented on arch/arm/configs/wirenboard7_defconfig
> -CONFIG_IPV6=y
Зачем?

2023-02-08 12:47 UTC, webconn commented on scripts/package/wb/do_build_bootpart.sh
> +    mkfs.ext2 $imgfile -L kernel+fdt
```suggestion
    /sbin/mkfs.ext2 $imgfile -L kernel+fdt
```

2023-02-08 12:47 UTC, webconn commented on scripts/package/wb/do_build_bootpart.sh
> +    resize2fs -M $imgfile
```suggestion
    /sbin/resize2fs -M $imgfile
```

2023-02-08 12:47 UTC, webconn commented on scripts/package/wb/do_build_bootpart.sh
> +
```suggestion
```

2023-02-08 19:51 UTC, evgeny-boger commented on arch/arm/configs/wirenboard7_defconfig
> -CONFIG_IPV6=y
это из-за savedefconfig. На самом деле CONFIG_IPV6 включен по-умолачнию, поэтому его в дефконфиге и не нужно

2023-02-09 13:04 UTC, webconn approved these changes

2023-03-07 18:22 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* disable eth1 */
может переименуем из -min в -nb? А то с отключением первого эзернета оно уже не так нужно кому-то, кроме одного клиента.

2023-03-07 18:22 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard734-wb7min.dts
> +/dts-v1/;
тут получилась копипаста коэффициентов из `-733.dts`.
Предлагаю вместо этого унаследоваться от 734.dts напрямую, вроде с этим не должно быть никаких проблем.

2023-03-07 18:22 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* disable 1-Wire on both pins */
надо бы написать коммент, что это делается для того, чтобы W1 и W2 использовать как дискретные входы обычные

2023-03-07 18:22 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +    regulators {
и здесь - что это отключает транзисторы подтяжки, чтобы их случайно не включил кто-то

2023-03-07 18:22 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* enable RS-485 */
и здесь коммент, про то что обычно это hwconf включает, а здесь включаем сами, чтобы без hwconf рабоатло

2023-03-07 18:22 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* enable RS-485 */
по-моему один из них кстати включен по-умолчанию

2023-03-09 08:37 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* enable RS-485 */
Да, uart2 включен, могу повторно не включать

2023-03-09 08:44 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* disable eth1 */
А что означает `-nb`? Мне не принципиально, как это назвать

2023-03-09 08:45 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard734-wb7min.dts
> +/dts-v1/;
Готово

2023-03-09 08:45 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* disable 1-Wire on both pins */
Готово

2023-03-09 08:45 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +    regulators {
готово

2023-03-09 08:45 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard7xx-min.dtsi
> +/* enable RS-485 */
Готово

2023-03-13 15:09 UTC, webconn commented
@evgeny-boger если всё устраивает, давай вливать

2023-07-04 23:40 UTC, closed without merging