add WBEC support for wb7 bootlet
wirenboard/linux pull request #143
Opened 2023-08-09 14:57 UTC by webconn

В бутлете не хватало модулей wbec и описаний gpio и wbec в dts для того, чтобы заработал скрипт обновления прошивки микроконтроллера. Ещё пин vin из 72х пересекается с gpio, нужными для обновления прошивки, так что vin был выключен (я так понимаю, бутлету не принципиально знать о состоянии зарядки).

2023-08-11 20:09 UTC, evgeny-boger requested changes

2023-08-11 20:09 UTC, evgeny-boger commented on arch/arm/boot/dts/sun8i-r40-wirenboard72x-bootlet.dts
> +/* This DTS is used only in FIT bootlets. For production version, use sun8i-r40-wirenboard72x-initram.dts */
чот я по названию и описанию не понял где какой.

Давай мы сделаем наоборот: initram оставим для того, который идёт в initramfs.
А для стенда производства сделаем новый. Ну и production не очень термин, так можно подумать что оно идёт во все контроллеры. factory-init может?

2023-08-11 20:09 UTC, evgeny-boger commented on arch/arm/configs/wirenboard7_initramfs_defconfig
> +CONFIG_GPIO_WBEC=m
а почему модулями?

2023-08-14 07:02 UTC, webconn commented on arch/arm/configs/wirenboard7_initramfs_defconfig
> +CONFIG_GPIO_WBEC=m
Вообще по аналогии с тем, как в большом ядре сделано, не знаю, может и не принципиально

2023-08-14 07:03 UTC, webconn commented on arch/arm/boot/dts/sun8i-r40-wirenboard72x-bootlet.dts
> +/* This DTS is used only in FIT bootlets. For production version, use sun8i-r40-wirenboard72x-initram.dts */
Переименовал

2023-08-14 12:33 UTC, vdromanov approved these changes
я погонял fit с этим ядром на старых wb7

на инициаллизации, FR, обновлении из webui;
претензий не имею

2023-08-18 07:13 UTC, webconn commented on arch/arm/configs/wirenboard7_initramfs_defconfig
> +CONFIG_GPIO_WBEC=m
Тоже переделал на builtin

2023-08-21 06:46 UTC, closed without merging

2023-08-21 06:46 UTC, webconn commented
Закрываю PR, сделаю его заново в основную ветку