Linux 6.8 rebase: WB8 RS-485 patches
wirenboard/linux pull request #221
Opened 2024-07-29 14:46 UTC by webconn

Шестой PR из серии, в которой мы проведём ревью всех изменений в ядро 6.8 для Wiren Board 8.

Здесь собраны все патчи в драйвер UART, которые нужны были для увеличения стабильности работы RS-485.

Я привязал задачу SOFT-4016 к исправлению вокруг флага NOTEMT, приложил в тикет переписку с одним из авторов кода, чтобы было понятно, куда копать при исправлении.

2024-07-30 06:40 UTC, sikmir approved these changes

2024-08-04 19:57 UTC, evgeny-boger requested changes
предлагаю всё-таки сделать как было в A40i у меня - отдельный PORT для олвиннера, а не хак в PORT_16550A

2024-08-05 06:30 UTC, webconn commented
я бы это очень хотел кому-нибудь делегировать. попробовал в лоб перетащить, оно не заработало сразу, за полчаса распутать не смог. там то ли autoconfig где-то в середине процесса инициализации прорезается, то ли ещё какая-то напасть.

под это я SOFT-4016 и завёл

2024-08-08 09:08 UTC, evgeny-boger approved these changes

2024-08-08 10:51 UTC, merged