Feature/wb85
wirenboard/linux pull request #229
Opened 2024-07-31 14:51 UTC by vdromanov

сделал dts для wb85; что-то сам потыкал; отдал Максу тыкать пристально

2024-07-31 15:02 UTC, vdromanov commented
я потыкал:
USB A
wifi
модем
gpio-модульки mod3-4

2024-08-04 20:06 UTC, evgeny-boger requested changes
как я понимаю, оно ещё завершения тестов у Максима ждёт

2024-08-04 20:06 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/Makefile
> +DTC_FLAGS_sun50i-h616-wirenboard85 := -@
851 может?

2024-08-04 20:06 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard85.dts
> +	model = "Wiren Board rev. 8.5 (T507)";
8.5.1

2024-08-04 20:06 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard85x.dtsi
> +	"", "", "", "CAN TX",  /* 4-7 */
по-моему тут опять забили сигналы правильно писать. Прошу всю табличку перепроверить

2024-08-06 10:48 UTC, vdromanov commented on arch/arm64/boot/dts/allwinner/Makefile
> +DTC_FLAGS_sun50i-h616-wirenboard85 := -@
готово!

2024-08-06 10:48 UTC, vdromanov commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard85.dts
> +	model = "Wiren Board rev. 8.5 (T507)";
готово!

2024-08-06 10:49 UTC, vdromanov commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard85x.dtsi
> +	"", "", "", "CAN TX",  /* 4-7 */
не забили; это же копипаста
но по табличке все равно проверил и не зря

а пусто здесь потому, что многое на вбек переехало

2024-08-07 05:51 UTC, webconn commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard8xx.dts
> +// This file is used only for updating via FIT
я бы тогда отдельный фит делал для бутлета, как в 7.x у нас было. Тут ведь явно было написано, что этот dts вообще для другого был нужен, а теперь мы его берём и переиспользуем

2024-08-07 15:14 UTC, vdromanov commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard8xx.dts
> +// This file is used only for updating via FIT
готово!

+ почекал, что новый fit устанавливается на старые wb8, а старый fit - не устанавливается на wb85

2024-08-08 05:55 UTC, webconn approved these changes

2024-08-09 11:52 UTC, vdromanov commented
обсудили с @webconn - решили копипастить dtsi (как с wb74), т.к. там @pgasheev нужно что-то с dts поковырять

![image](https://github.com/user-attachments/assets/d20cdfae-a3a8-4ff8-a0a0-21dc31a71eba)

2024-08-16 07:54 UTC, webconn commented on debian/changelog
> +  * remane modules: mod2 -> mod3; mod3 -> mod4; mod4 -> mod2
```suggestion
  * rename modules: mod2 -> mod3; mod3 -> mod4; mod4 -> mod2
```

а вообще это точно нужная запись в ченджлог? для wb8.4 ведь ничего не поменялось?

2024-08-16 08:09 UTC, vdromanov commented on debian/changelog
> +  * remane modules: mod2 -> mod3; mod3 -> mod4; mod4 -> mod2
кмк, нужная
я вот по чейнжлогу обычно вспоминаю, что происходит

предлагаю дописать, что это про 85

2024-08-16 08:10 UTC, vdromanov commented on debian/changelog
> +  * remane modules: mod2 -> mod3; mod3 -> mod4; mod4 -> mod2
хотя не нужна: у нас 85 никуда не выкатывался; уберу

2024-08-20 12:17 UTC, vdromanov commented
отребейзили - влили

2024-08-20 12:17 UTC, closed without merging