Feature/3930 fast microsd
wirenboard/linux pull request #257
Opened 2024-10-07 08:02 UTC by taraant

Реализовал драйвер для MicroSD, который задействует встроенных регулятор напряжения H616, для работы в скоростных режимах SD-UHS.

На части протестированных флешках не работает на скоростях 150Мгц (ошибка при записи из буфера на флешку). По-этому урезал до 120Мгц - на ней работает стабильно.

Выдает:
```
root@wirenboard-AGQWPRTR:~# cat /sys/kernel/debug/mmc1/ios 
clock:		120000000 Hz
actual clock:	120000000 Hz
vdd:		21 (3.3 ~ 3.4 V)
bus mode:	2 (push-pull)
chip select:	0 (don't care)
power mode:	2 (on)
bus width:	2 (4 bits)
timing spec:	6 (sd uhs SDR104)
signal voltage:	1 (1.80 V)
driver type:	0 (driver type B)
```

```
root@wirenboard-AGQWPRTR:~# dd if=/dev/random of=/dev/mmcblk1 status=progress bs=1M
4057989120 байт (4,1 GB, 3,8 GiB) скопирован, 129 s, 31,4 MB/s^C
3881+0 записей получено
3881+0 записей отправлено
4069523456 байт (4,1 GB, 3,8 GiB) скопирован, 142,262 s, 28,6 MB/s
```

```
root@wirenboard-AGQWPRTR:~# dd if=/dev/mmcblk1 of=/dev/null status=progress bs=1M
4294967296 байт (4,3 GB, 4,0 GiB) скопирован, 79 s, 54,4 MB/s^C
4104+0 записей получено
4103+0 записей отправлено
4302307328 байт (4,3 GB, 4,0 GiB) скопирован, 79,9615 s, 53,8 MB/s
```

Скорость зависит от флешки и это максимум из тех, что у меня есть в наличии.

2024-10-07 11:22 UTC, evgeny-boger requested changes
должен быть ещё yaml с dt-биндингами, плюс прогнать через проверку его - там таргет в make есть для этого

2024-10-07 11:22 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +	compatible = "allwinner,sun50i-h616-pinctrl", "syscon";
что это и зачем?

2024-10-07 11:22 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +    max-frequency = <120000000>; // 150Mhz dont work
пожалуйста исправь форматирование

2024-10-07 11:22 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +	/* sd-uhs-ddr50;  // Dont work */
а почему ddr50 не работает?

2024-10-07 11:22 UTC, evgeny-boger commented on drivers/regulator/Kconfig
> +      This driver supports the PMMC regulator found in Allwinner sunxi SoCs,
в описании бы подробнее написать

2024-10-07 11:22 UTC, evgeny-boger commented on drivers/regulator/h616-mmc-regulator.c
> +    .name = "h616-mmc-vqmmc",
патч прогнать через check_path.pl

2024-10-08 17:44 UTC, taraant commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +	compatible = "allwinner,sun50i-h616-pinctrl", "syscon";
В данном случае я объявил устройство pio совместимым с syscon и после по нему получил regmap:    
    regmap = syscon_regmap_lookup_by_phandle(pdev->dev.of_node, "syscon");
    
Сделал так, потому что к регистрам не могу напрямую обращаться (т.к. они уже используются узлом pio), а сделать регулятор дочерним для &pio не могу (ну чтобы получить regmap родительского), так как pio не настроен как поддерживающий дочерние устройства (можно попробовать приделать simple-mfd или simple-bus вместо syscon, но модифицировать все равно нужно).

2024-10-08 17:49 UTC, taraant commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +    max-frequency = <120000000>; // 150Mhz dont work
Не понимаю: что тут не так?
пустая строка?

2024-10-09 06:48 UTC, taraant commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +	/* sd-uhs-ddr50;  // Dont work */
На самом деле флешка должна поддерживать этот режим. Пробовал на всех доступных, только на этом режиме - ни одна не завелась. Отключил на всякий.

2024-10-09 06:54 UTC, taraant commented on drivers/regulator/Kconfig
> +      This driver supports the PMMC regulator found in Allwinner sunxi SoCs,
This driver supports the MMC voltage regulator used in Allwinner Sunxi SoCs, which allows switching the voltage levels of the MicroSD data lines from 3.3V to 1.8V.
This regulator is required to support high-speed SD-UHS modes. Without it, the microSD will operate in "slow" modes.

Норм?

2024-10-09 07:05 UTC, taraant commented on drivers/regulator/h616-mmc-regulator.c
> +    .name = "h616-mmc-vqmmc",
+

2024-10-10 08:34 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +	compatible = "allwinner,sun50i-h616-pinctrl", "syscon";
а внутри pnctrl точно нет стандартного интерфейса для смены напряжений пина/пада?

2024-10-10 08:34 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +    max-frequency = <120000000>; // 150Mhz dont work
отступ строчек разный

2024-10-10 08:35 UTC, evgeny-boger commented on arch/arm64/boot/dts/allwinner/sun50i-h616-wirenboard84x.dtsi
> +	/* sd-uhs-ddr50;  // Dont work */
это что-то у нас в драйвере, до этого тоже не работало у коллег. Напиши коммент получше

2024-10-10 08:35 UTC, evgeny-boger commented on drivers/regulator/Kconfig
> +      This driver supports the PMMC regulator found in Allwinner sunxi SoCs,
я думаю важно тут, что это не какой-то внешний регулятор, а что оно переключает напряжение между этим и тем входами

2024-12-07 02:27 UTC, merged