Update rtl8733bu submodule to use branch v5.15.12-126-wb
wirenboard/linux pull request #269
Opened 2024-11-01 05:46 UTC by taraant

Обновил версию драйвера WiFi до v5.15.12-126-wb (версия от производителя + наши изменения)

2024-11-01 08:13 UTC, KraPete requested changes
Мы ж в конфиге параметр назвали XXX_WB, было XXX_WB7. Кажется, теперь вообще никакой драйвер не собрается с ядром

2024-11-01 08:13 UTC, KraPete requested changes

2024-11-01 08:13 UTC, KraPete commented on debian/changelog
> +linux-wb (6.8.0-wb114) stable; urgency=medium
Версия не изменилась

2024-11-01 08:54 UTC, KraPete commented
> Мы ж в конфиге параметр назвали XXX_WB, было XXX_WB7. Кажется, теперь вообще никакой драйвер не собрается с ядром

Разобрался, это не актуально, но версию  надо сменить

2024-11-01 10:28 UTC, sikmir commented on debian/changelog
> + -- Anton Tarasov <anton.tarasov@wirenboard.com> Fri, 1 Nov 2024 08:42:51 +0300
```suggestion
 -- Anton Tarasov <anton.tarasov@wirenboard.com>  Fri, 01 Nov 2024 08:42:51 +0300
```

2024-11-02 11:28 UTC, taraant commented
> Мы ж в конфиге параметр назвали XXX_WB, было XXX_WB7. Кажется, теперь вообще никакой драйвер не собрается с ядром

Не, версия указанная в ядре и версия указанная в Makefile драйвера - это разные вещи.

2024-11-02 14:07 UTC, closed without merging