Feature/wb6.7.0
wirenboard/linux pull request #34
Opened 2020-08-25 10:10 UTC by vdromanov

1) сигналы из этой [задачи](https://wirenboard.bitrix24.ru/company/personal/user/61/tasks/task/view/23218/)
2) V_OUT_ST на всех контроллерах был подтянут резистором к верху, а в dts - к низу
3) ошибка в dts: uart8 был не на том aips

последний месяц+ WB6.7 ходят по столам с этим ядром

2020-08-25 22:52 UTC, evgeny-boger requested changes

2020-08-25 22:52 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard61.dts
> +				iio-device = <&adc1>;
зачем здесь исправления пробелов в этом PR? Неудобно будет потом смотреть по истории, стоит убрать отсюда.

2020-08-25 22:52 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	lcdspidev:	lcd-display@0{
мы ещё не знаем, какой там будет дисплей и будет ли вообще. Думаю, нужно оставить просто spi-ноду и всё.

2020-08-25 22:52 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	fsl,pins = <
отступы

2020-08-25 22:52 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +		MX6UL_PAD_JTAG_MOD__GPIO1_IO10		0x80000000 /* SPDIF_OUT connected to MODULE 2 TX PIN via 3K, must be high when i2c*/
Что такое 0x800000000 ?
Почему в старых платах этого нет?

2020-08-25 22:52 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	rts-gpios = <&gpio4 19 GPIO_ACTIVE_LOW>;
написать бы комментарий, что это за уарт

2020-08-25 22:52 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +/dts-v1/;
огромный дифф как бы намекает, что пора по-другому разбить dts: выделить общий кусок для 6.x отовсюду и инклюдить его, а не пытаться делать патчи 6.1-6.5-6.6-6.7. Но лучше это сделать потом и отдельным PR.

2020-08-25 22:52 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	pinctrl_spilcd: spilcdgrp {
это в итоге в ноде экрана должно использоваться?

2020-08-28 08:00 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard61.dts
> +				iio-device = <&adc1>;
готово

2020-08-28 08:09 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	pinctrl_spilcd: spilcdgrp {
да
раз убираем ноду экрана, убрал и pinctrl

2020-08-28 08:09 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	lcdspidev:	lcd-display@0{
убрал

2020-08-28 08:11 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	rts-gpios = <&gpio4 19 GPIO_ACTIVE_LOW>;
готово

2020-08-28 08:19 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +		MX6UL_PAD_JTAG_MOD__GPIO1_IO10		0x80000000 /* SPDIF_OUT connected to MODULE 2 TX PIN via 3K, must be high when i2c*/
это [из 6.1](https://github.com/wirenboard/linux/blob/ef2d87e222b365848fe7262c022ca887b6449432/arch/arm/boot/dts/imx6ul-wirenboard61.dts#L811) приехало

2020-08-28 08:20 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	fsl,pins = <
убрал pinctrl

2020-08-28 08:30 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +/dts-v1/;
сделал задачу в группе софта

2020-08-28 08:49 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
> +	pinctrl_spilcd: spilcdgrp {
а это как раз зря: pinctrl нельзя потом в рантайме в hwconf определить, так что его правильно оставлять в ядре.

2020-08-28 10:49 UTC, merged