Feature/wb6.7.0
wirenboard/linux pull request #36
Opened 2020-08-28 20:07 UTC by vdromanov

1. Пока занимался тест-сьютом, отловил проблему с оверлеями. Виновато удаление ноды spi-rfm (старое радио), чтобы освободить его пины для wb6.7. Чтобы не конфликтовать с wb6-noradio и освободить пины, сделал пустую ноду spi-rfm.

2. Информация о модеме по умолчанию (в ноде wirenboard): status - disabled; model - none. Можно не записывать оверлей wb6-nogsm (uart тоже отключен)

2020-08-28 22:55 UTC, evgeny-boger requested changes

2020-08-28 22:55 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
>  			power-gpios = <&gpio5 4 0>;
проблема в том, что status в юзерспейсе никто не проверяет. Если нужна нода - давай делать пустую ноду.

2020-08-28 22:55 UTC, evgeny-boger commented on arch/arm/boot/dts/imx6ul-wirenboard65.dts
> +		compatible = "spi-gpio";
зачем тут compatible?

2020-08-31 09:26 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard670.dts
>  			power-gpios = <&gpio5 4 0>;
убрал

2020-08-31 09:26 UTC, vdromanov commented on arch/arm/boot/dts/imx6ul-wirenboard65.dts
> +		compatible = "spi-gpio";
тут вообще пустой ноды хватит

2020-08-31 09:27 UTC, vdromanov commented
Про радио - перенёс в [другой](https://github.com/wirenboard/linux/pull/37) PR. Этот PR закрываю

2020-08-31 09:27 UTC, closed without merging