wb-deb: linux 4.9.22
wirenboard/linux pull request #50
Opened 2021-04-02 10:25 UTC by webconn

Добавил прямо в дерево скрипт, который собирает deb-пакет с ядром. Сделан на основе скрипта `builddeb` из ядра и скриптов из `build_kernel` в качестве фронтенда.

Плюс, здесь же теперь есть Jenkinsfile, который позволяет собирать пакеты автоматически на CI.

2021-04-02 11:39 UTC, webconn commented
Забыл добавить создание симлинка на zImage, переложил в draft

2021-04-02 13:42 UTC, evgeny-boger commented
а зачем вообще zImage симлинком?

2021-04-02 13:48 UTC, webconn commented
Было легко добавить (списал из патча `builddeb` в `armbian`). В принципе и файлом можно, тут особой разницы нет.

2021-04-02 13:54 UTC, evgeny-boger commented on Jenkinsfile
> +            // TODO: common checkout to a local storage can save time if you are building different branches
А сейчас оно делает полный clone с интернета каждый раз?

2021-04-02 13:54 UTC, evgeny-boger commented on scripts/package/wb/version.sh
> +setup_kernel_vars() {
а почему `version.h` ?
Как-то содержание не соответствует

2021-04-02 13:54 UTC, evgeny-boger commented on Jenkinsfile
> +                                   KERNEL_FLAVOUR=${currentFlavour} \\
давай уже сделаем нормальные опции командной строки, а не этот ужас с передачей обязательных параметров через переменные окружения.

2021-04-02 13:57 UTC, webconn commented on scripts/package/wb/version.sh
> +setup_kernel_vars() {
Копипаста из `build_kernel`

2021-04-02 13:59 UTC, webconn commented on Jenkinsfile
> +            // TODO: common checkout to a local storage can save time if you are building different branches
Если только ветку раньше не собирали. И не совсем полный, там в настройках Jenkins я указал на загрузку истории не более чем на 1000 коммитов. Минут 10-15 с нуля это занимает.

Если обновлять уже собранную ранее ветку, то используется ранее загруженные сырцы и на подтягивание изменений уходят секунды.

2021-04-02 14:01 UTC, webconn commented on Jenkinsfile
> +                                   KERNEL_FLAVOUR=${currentFlavour} \\
Опять же, не хотел это переделывать. Парсить красивые опции в `bash` не очень приятно, а так они все проименованы и кода почти не требует.

2021-04-03 21:55 UTC, evgeny-boger approved these changes

2021-04-04 19:54 UTC, evgeny-boger requested changes
что-то я ещё раз посмотрел и стал думать, что, может быть, с версиями надо как-то по-другому поступать.

Во всех остальных местах же у нас есть явный Changelog. Это просто и понятно для всех.

А тут у нас опять будут непонятные названия версий, опять надо будет как-то дико по гиту искать, что в них поменялось. 
А с учётом ребейзов искать надо будет по всем веткам.

Я предлагаю сделать явный Changelog и явно брать версию из него.

2021-04-05 03:47 UTC, PeteK12 commented on scripts/package/wb/do_build_deb.sh
> +#!/bin/bash -e
Можно доку на это? Какие переменные окружения за что отвечают и какие могут быть их значения.

2021-04-05 06:31 UTC, webconn commented
> что-то я ещё раз посмотрел и стал думать, что, может быть, с версиями надо как-то по-другому поступать.
> 
> Во всех остальных местах же у нас есть явный Changelog. Это просто и понятно для всех.
> 
> А тут у нас опять будут непонятные названия версий, опять надо будет как-то дико по гиту искать, что в них поменялось.
> А с учётом ребейзов искать надо будет по всем веткам.
> 
> Я предлагаю сделать явный Changelog и явно брать версию из него.

Changelog при перетаскивании ребейзами может поломаться, надо будет за ним особо следить и так далее.На самом деле, я бы в таком случае вообще предлалагаю генерировать changelog из истории гита, накладывая туда названия коммитов и даже авторов можно (gbp-buildpackage это умеет делать из коробки)

2021-04-05 13:55 UTC, evgeny-boger commented
а как он поломается от ребейзов?

Как раз история гита поломается, а файл - нет.
Я хочу при ребейзе на следующую версию линукса сливать все наши коммиты в минимальный набор. Т.е. мы фактически поддерживаем набор патчей поверх линукса. Так из истории гита ничего не сделать.

2021-04-06 06:19 UTC, webconn commented on scripts/package/wb/do_build_deb.sh
> +#!/bin/bash -e
Добавил

2021-04-06 08:51 UTC, webconn commented
Сделал статичный changelog. Для сборки пакета решил оставить модифицированный builddeb, теперь он вместо генерирования changelog берёт готовый, оттуда же берёт и ревизию ядра.

Осталась возможность собирать пакет с ядром с суффиксом версии в ветках, примеры в Jenkins.

2021-04-08 00:04 UTC, evgeny-boger approved these changes

2021-04-08 13:46 UTC, PeteK12 approved these changes

2021-04-08 13:56 UTC, merged