rts on rs485 uarts is configured as gpio with default PD
wirenboard/linux pull request #56
Opened 2021-04-22 15:17 UTC by vdromanov

в ядре 5.10 появился механизм для решения старой проблемы с трансиверами rs485 (в idle удерживали шину в передающем состоянии)

rts у трансиверов теперь настроен, как gpio c подтяжкой вниз

2021-04-22 15:19 UTC, webconn commented
Не забудь добавить запись в debian/changelog, теперь тут так принято )

2021-04-23 09:47 UTC, evgeny-boger requested changes
давай заодно для модулей расширения это сделаем. Я только не помню сходу, здесь это надо делать или только в оверлеях hwconf

2021-04-29 13:47 UTC, vdromanov commented
Сделал то же самое для модулей расширения. Со стороны hwconf ничего менять не надо: одни и те же pinctrl настроены по-разному в ядрах 4.9 и 5.10

Проблема с неработающими модулями расширения решалась Иваном Заенцевым [в hwconf](https://github.com/wirenboard/wb-hwconf-manager/commit/42010fcd54d1ec1b3d91de27a9666d9ad01813cc) => нужно зависеть от hwconf.

Зависимость от нужного нам hwconf уже была реализована [здесь](https://github.com/wirenboard/build_kernel/commit/979564799f3ca03f98941e515af26c295c14acd0). => пока прописал Conflicts: в скрипте сборки.
@webconn нужно не забыть перенести это в новую систему сборки ядра

2021-04-29 13:52 UTC, webconn commented
@vdromanov, ты сам всё правильно сделал :)
Можешь тогда сразу эти строчки туда добавить, с остальными зависимостями?
```
diff --git a/scripts/package/wb/builddeb b/scripts/package/wb/builddeb
index 07523fb9225a..f95b1a355931 100755
--- a/scripts/package/wb/builddeb
+++ b/scripts/package/wb/builddeb
@@ -328,7 +328,8 @@ else
 Package: $packagename
 Provides: linux-image, linux-image-2.6, linux-modules-$version
 Breaks: linux-image-4.9.22-$wb_target (<< $packageversion)
-Replaces: linux-image-4.9.22-$wb_target (<< $packageversion)
+Replaces: linux-image-4.9.22-$wb_target (<< $packageversion), linux-image-4.1.15-imxv5-x0.1, linux-image-4.9.6-wb
+Conflicts: linux-image-4.1.15-imxv5-x0.1, linux-image-4.9.6-wb, wb-configs (<= 1.72), wb-hwconf-manager (<< 1.38.3)
 Suggests: $fwpackagename
 Architecture: any
 Description: Linux kernel, version $version, $wb_description
```

2021-04-29 18:50 UTC, merged