ADS1115 detection
wirenboard/linux pull request #92
Opened 2022-06-01 07:00 UTC by KraPete

Some WBIO-AI-DV-12 can have ADS1115 instead of ADS1015. They have different conversion times.
Using ti-ads1015 driver for them will lead to reading wrong values.
To detect such devices driver uses Lo_thresh register.
4 LSB in ADS1015's Lo_thresh register are read only, they are always zero.
ADS1115's Lo_thresh is completely writable.
Driver writes 0xFF and reads value back.
If they are equal, it is ADS1115, and appropriate conversion times are used.

![изображение](https://user-images.githubusercontent.com/86825564/171346588-2dd03f1a-39c4-4746-9716-8044eeec4633.png)

2022-06-02 09:09 UTC, webconn approved these changes

2022-06-02 09:10 UTC, webconn commented on drivers/iio/adc/ti-ads1015.c
> +			dev_err(&client->dev, "The device is not ADS1015, seems to be ADS1115\n");
Может, сделаем тут warn или info вообще, а то пользователи вдруг начнут нервничать?

2022-06-02 09:34 UTC, KraPete commented on drivers/iio/adc/ti-ads1015.c
> +			dev_err(&client->dev, "The device is not ADS1015, seems to be ADS1115\n");
Делал `warn`. Оно вообще не видно. Там шрифт чуть толще чем обычный info. Никто не увидит. Потому наоборот сделал `err`.

2022-06-02 09:49 UTC, webconn commented on drivers/iio/adc/ti-ads1015.c
> +			dev_err(&client->dev, "The device is not ADS1015, seems to be ADS1115\n");
Вопрос в том, надо ли это кому-то видеть, если мы это предполагаем как заводское решение

2022-06-02 11:11 UTC, KraPete commented on drivers/iio/adc/ti-ads1015.c
> +			dev_err(&client->dev, "The device is not ADS1015, seems to be ADS1115\n");
Сделал `dev_warn`

2022-06-02 11:12 UTC, webconn approved these changes

2022-06-10 10:36 UTC, evgeny-boger requested changes
если честно, мне не нравится.

Я думаю, что в ядро надо стараться писать так, чтобы изменения можно было не стыдно отправить наверх. А сейчас мы сделали грязный хак и ещё об этом честно и громко написали.

Предлагаю вместо этого вставить автоопределение в probe, например сюда https://github.com/wirenboard/linux/blob/0c15f62a23f67ade71c7b109a591bf4247e25ecf/drivers/iio/adc/ti-ads1015.c#L1007

Добавить новый match в ads1015_of_match типа ti,ads1x15.
Добавить его в DT схему.

Подать в коммит-мессейдже это не как костыль для нашей ошибке, а как фичу, которая позволяет взаимозаменяемо использовать ads1015 и ads1115

2022-06-10 10:47 UTC, KraPete commented
> если честно, мне не нравится.
> 
> Я думаю, что в ядро надо стараться писать так, чтобы изменения можно было не стыдно отправить наверх. А сейчас мы сделали грязный хак и ещё об этом честно и громко написали.
> 
> Предлагаю вместо этого вставить автоопределение в probe, например сюда
> 
> https://github.com/wirenboard/linux/blob/0c15f62a23f67ade71c7b109a591bf4247e25ecf/drivers/iio/adc/ti-ads1015.c#L1007
> 
> Добавить новый match в ads1015_of_match типа ti,ads1x15. Добавить его в DT схему.
> 
> Подать в коммит-мессейдже это не как костыль для нашей ошибке, а как фичу, которая позволяет взаимозаменяемо использовать ads1015 и ads1115

Согласен, с точки зрения ядра это лучше. Но мы сломаем своим клиентам обратную совместимость. Раньше были настройки scale и data_rate от 1015, после такого обновления они поменяются на настройки от 1115. Если никто ими не пользовался, то не страшно, но если кто-то что-то писал в них, т.к. они выставлены как файлики в user space, будет сюрприз.

2022-06-15 09:04 UTC, closed without merging